# Generated by Django 5.2.7 on 2025-10-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guests_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('room_number', models.IntegerField()),
                ('number_of_days', models.IntegerField()),
                ('number_of_nights', models.IntegerField()),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
