# Generated by Django 5.2.7 on 2025-10-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests_registration',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
