# Generated by Django 5.2.7 on 2025-10-28 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests_site', '0002_rename_fist_name_guests_registration_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests_registration',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
